##
# database build script
##

import os
Import('homebrain_env')

db_env = homebrain_env.Clone()

db_env.AppendUnique(CPPPATH = [
    '..',
    'src',
    ])

db_src = [
    'src/HBDatabase.cpp',
    'src/HBGlobalTable.cpp',
    'src/RuleEngineTable.cpp',
    'src/SceneEngineTable.cpp',
    'src/DeviceProfileTable.cpp',
    'src/GatewayConnectTable.cpp',
    'src/OCFDeviceTable.cpp',
    ]

db_env.PrependUnique(LIBS=[
    'sqlite3',
])

shared_libdatabase = db_env.SharedLibrary('HB_StorageTable', db_src)
db_env.InstallTarget(shared_libdatabase, 'HB_StorageTable')
